name: frequenz-api-microgrid

on: [pull_request, push, release]

jobs:
  protolint:
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get protolint
        run: |
          # checksum taken from: https://github.com/yoheimuta/protolint/releases/download/v0.38.1/checksums.txt
          echo "c1a43f352da6f96f3e60efe33438eaca6148526e6145d9bbd77c40cebc9895a6  protolint_0.38.1_Linux_x86_64.tar.gz" > checksum.txt

          curl -LO https://github.com/yoheimuta/protolint/releases/download/v0.38.1/protolint_0.38.1_Linux_x86_64.tar.gz \
          && sha256sum --check checksum.txt \
          && tar xf protolint_0.38.1_Linux_x86_64.tar.gz \
          && chmod +x protolint \
          && sudo mv protolint /usr/local/bin/protolint

      - name: Run protolint
        run: protolint lint proto

  tests:
    needs: ["protolint"]
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox build

      - name: Build the Python package
        run: python -m build

      - name: Run tox
        run: tox -r
